# Generated by Django 3.2.9 on 2021-12-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator_name', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('evaluations', models.TextField()),
            ],
        ),
    ]
