# Generated by Django 3.2.9 on 2021-12-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0004_evaluationsheet_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
