# Generated by Django 3.2.9 on 2022-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0012_alter_evaluationsheet_evaluator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('job understanding', 'Job Understanding'), ('job skills', 'Job Skills'), ('attitude', 'Attitude'), ('job rules and regulations', 'Job Rules and Regulations')], max_length=255)),
            ],
        ),
    ]
