# Generated by Django 3.2.9 on 2022-03-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0014_auto_20220314_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='can_evaluate',
            field=models.BooleanField(default=True),
        ),
    ]
