# Generated by Django 3.2.9 on 2022-03-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0015_appuser_can_evaluate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='can_evaluate',
        ),
    ]
