# Generated by Django 3.2.9 on 2022-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0016_remove_appuser_can_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
