# Generated by Django 3.2.9 on 2022-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0018_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='company_logo',
            field=models.BooleanField(default=False),
        ),
    ]
