# Generated by Django 4.0.5 on 2022-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0019_image_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=1024)),
            ],
        ),
    ]
