# Generated by Django 4.0.5 on 2022-06-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0020_evaluationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgroup',
            name='close_date',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='evaluationgroup',
            name='open_date',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
