# Generated by Django 4.0.5 on 2022-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0021_evaluationgroup_close_date_evaluationgroup_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='evaluate_group',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
