# Generated by Django 4.0.5 on 2022-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0022_questioncategory_evaluate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsheet',
            name='evaluate_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
