# Generated by Django 4.0.5 on 2022-06-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0024_remove_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='evaluate_group',
        ),
    ]
