# Generated by Django 4.0.5 on 2022-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0025_remove_questioncategory_evaluate_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategoryBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.IntegerField(default=0)),
                ('category_id', models.IntegerField(default=0)),
            ],
        ),
    ]
