# Generated by Django 4.0.5 on 2022-06-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0027_categoryevaluationbrige'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryEvaluationBrige',
            new_name='CategoryEvaluationBridge',
        ),
    ]
